### ISSUE TITLE
Be able to define computed properties on related models..

### ISSUE THREAD

**Issue by kimf** [brianpattison/motion-loco#3]
Hello there, as a Ember user I'm loving this.

One thing that is more of a "nice to have" then an actual bug is the possibility to define computed properties using for example the has_many relationship.._

```
class Score < Loco::Model
   property :strokes, lambda{|object|
     object.shots.count
   }.property('shots.length')

   has_many :shots
end
```

**Comment by brianpattison** [comment]
Yeah, good call. I definitely want things to work as Ember users would expect.

Now that you mention it, I'm honestly not sure if arrays even work as expected when defining computed properties. Something I'll have to look into.

If you have a chance to write some failing tests for the behavior you're expecting, that would be great. Passing tests would be even better. ;)

**Comment by kimf** [comment]
Started to write some tests for it, if I have the time I will look into it this weekend.

**Comment by brianpattison** [comment]
I plan on  looking into it this weekend as well, so if you can get me some tests, even as a gist, that would help a lot. Thanks!

**Comment by kimf** [comment]
Hello again.. The time slipped away from me this weekend, do you still need/want the tests?

**Comment by brianpattison** [comment]
Yes, that'd still be appreciated. I ended up digging myself into a hole this weekend trying to consolidate the data adapter tests. And by that I mean I ended up with important tests that don't pass. I got pretty close though. The has_many relationships still need some work. https://github.com/brianpattison/motion-loco/tree/combine_adapter_tests

So what I'm looking for is tests for computed properties on relationships, both belongs_to and has_many relationships. Just like what you described, plus testing belongs_to.

``` ruby
class Score < Loco::Model
  property :player_name, lambda{|object|
    object.player.name
  }.property('player.name')
  property :strokes, lambda{|object|
    object.shots.count
  }.property('shots.length')

  belongs_to :player
  has_many :shots
end
```

The tests for the has_many relationships should maybe test observing the length of arrays first, without even being defined as a relationship. So that would be a test for `Loco::Observable` while the relationship tests would be for `Loco::Model`.

Anything helps, thanks!

**Comment by brianpattison** [comment]
So this is a tricky one...

I'm using KVO for watching key paths like `player.name`, but because `player` is defined using `define_method`, RubyMotion doesn't know about it when compiling and says it can't be accessed by Objective-C when the KVO wants to watch the path. I think it only happens if the property hasn't been used before, but I'm not totally sure about that.

I'm not really sure what to do at this point, but I'm finally working on an iOS project full-time that's actually using Motion-Loco! I'm finding and fixing issues a lot faster now, so hopefully I can come up with a good solution to this one. I need one!

**Comment by kimf** [comment]
Im closing this :dancer:
